# Site settings
title: Amrinder Sandhu
email: amrinder@outlook.in
description: "Amrinder Singh Sandhu is a UX/UI designer from Ancaster, Canada. He designs web and mobile apps."
baseurl: ""
url: "https://amrindersandhu.com/"
future: true

# Build settings
markdown: kramdown