
journal:
- {	title: 'Interesting approach for managing your commits.', 
	url: 'https://hofmannsven.com/2019/commit-message-driven-development',
	author: 'Sven Hofmann',
	content-title: 'Commit Message Driven Development',
	content-copy: 'In software development, we usually start with writing the code. But what if we’d start by writing out the commit message? Follow me through the concept of commit message driven development.'
}

- {	title: 'How to increase focus to solve challenging problems by minimizing distractions.',
	url: 'https://www.smashingmagazine.com/2019/11/better-design-deep-thinking/',
	author: 'Smashing Magazine',
	content-title: 'Better Design With Deep Thinking',
	content-copy: 'Task switching is a design killer. Find out why switching and interruptions are even more serious than you think and how biology makes it difficult to resist the temptation to just check your email every few minutes. Learn how to slay the distraction dragon with five practical tips for increasing focus as you tackle challenging design problems.'
}

- {	title: 'Some useful tips on how to impress your new boss early on.', 
	url: 'https://knowyourteam.com/blog/2019/09/24/how-to-impress-your-new-boss-in-your-first-30-days/" target="_blank',
	author: 'Know Your Team',
	content-title: 'How to impress your new boss in your first 30 days',
	content-copy: 'Exceed expectations • Display excellent writing skills • Accept feedback willingly • Give feedback willingly • Be eager – but set expectations • Be a “manager of one” • Be empathetic • Small gestures make meaningful impact'
}

- {	title: '7 interesting things that made Briana working at Stripe feel different.', 
	url: 'https://knowyourteam.com/blog/2019/09/24/how-to-impress-your-new-boss-in-your-first-30-days/',
	author: 'Sven Hofmann',
	content-title: 'Brianna @zebriez',
	content-copy: 'I recently left Stripe after 4.5 formative and magical years. Some reflections on what made working at Stripe feel different than working other places:<br>1/Turpentine<br>2/Writing<br>3/Meticulousness<br>4/Principled decision-making<br>5/Ambition<br>6/Talking up<br>7/The API metaphor'
}

- {	title: 'Empathy isn’t about being nice but it can help increase revenue.', 
	url: 'https://vimeo.com/343056801',
	author: 'Vimeo • 99U',
	content-title: 'Michael Ventura: Empathy is your Best Creative Tool',
	content-copy: 'Entrepreneur and author Michael Ventura has dedicated his career to exploring how empathy can make us better leaders, collaborators, and contributors to society. In his 99U talk, Michael explains that the practice of empathy “isn’t about being nice” — it’s about deep understanding, and learning to apply that understanding to incredibly effective ends.'
}





branding:
- {	
	url: 'https://www.amazon.com/Logo-Design-Love-Creating-Identities/dp/0321985206',
	name: 'Logo design love',
	author: 'by David Airey'
}

- {	
	url: 'https://www.amazon.com/Designing-Brand-Identity-Essential-Branding/dp/1118099206',
	name: 'Designing brand identity',
	author: 'by <em>Alina Wheeler</em>'	
}




business:
- {	
	url: 'https://www.amazon.com/Why-We-Fail-Learning-Experience/dp/1933820179',
	name: 'Why we fail',
	author:  'by <em>Victor Lombardi</em>'	
}

- {	
	url: 'https://www.amazon.com/Hacking-Growth-Fastest-Growing-Companies-Breakout/dp/045149721X',
	name: 'Hacking growth',
	author: 'by <em>Morgan Brown</em> and <em>Sean Ellis</em>'	
}

- {	
	url: 'https://www.amazon.com/Trendology-Advantage-Data-Driven-Real-Time-Marketing/dp/1137479558',
	name: 'Trendology',
	author: 'by <em>Chris Kerns</em>'	
}

- {	
	url: 'https://www.amazon.com/Sense-Respond-Successful-Organizations-Continuously/dp/1633691888',
	name: 'Sense and respond',
	author: 'by <em>Jeff Gothelf </em>and <em>Josh Seiden</em>'	
}

- {	
	url: 'https://www.amazon.com/Experience-Required-become-leader-regardless/dp/0134398270',
	name: 'Experience required',
	author: 'by <em>Hoekman Jr Robert</em>'	
}

- {	
	url: 'https://www.amazon.com/Extreme-Revenue-Growth-Startup-Industry/dp/0984183515',
	name: 'Extreme revenue growth',
	author: 'by <em>Victor Cheng</em>'	
}



